import Navbar from '@/components/Navbar'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Philosopher, Poppins } from 'next/font/google';

const philosopher = Philosopher({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-philosopher',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sitio de recetas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`bg-[#05081F] min-h-full flex flex-col text-white ${philosopher.variable} ${poppins.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
